language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: ga+KIbNgtBbLByrb9lvp4QWqDjI0ldot/o0NsNb4CcqnG/oNBpPhfw8557bDFzCoDbbYLgj7gd38XBMhWmHzx82NGllCKsgQwZU2RmdwMTdMRdP1kQ5LRvY4h0VDI030bQU5hpWYXq2hrgC2eFaxSuxeM1XIIhIrXQXVxW+PU5bUHDtzSs2Rhmdk+QhHJ1GLHhXqob1AHlh8O6wawdZj7YAE1kymitTE0wrPvAo7Uy4hBzKHvV2ov78reItiLJ+DoBHO22FMLqAggyJ5ITLQXg/GKog/H7ak3Y4WQtX1ev0VbYzSZRSr3p6+f3/E+GWiJcBKRrThNnQ+EUWXPErO6WkxYDm5WkfOjkoRD0O0gRtDBZy6sN8owbsZOPQQFRBe3YjPRYBSrc22lsOWnM84Wy39WPLkvpD3Y9WA1DUVCDPtbB6SIBNUPwq/z6mK3eL4y1WYqOr/24dkU/r6ss3nWsgiMYNqK+htrh0GrIRSrKFreM9bgSYqn5632AwQzjNGIfy7JfNrbgNIdQ4O4eVu/BF2o90K/5fw/FJuwX3kRhtI8Hix5JYDDjRmr4miP4KekbGiyDLydi7Sfd7RHPFDhljDadQzHGVBNJJQd6J+FBBXj7z6QX6Hb46a227C3k3TPCqxl051yBq3NeXUJIuJJxrpj9ETpF/NFUqx0y7Hc+E=
